/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.dj.explorer;

import javax.swing.JComponent;
import org.dj.domainmodel.api.DJNodeObject;
import org.dj.node.api.DJNode;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.explorer.view.ListView;
import org.openide.explorer.view.TreeView;
import org.openide.nodes.Node;
import org.openide.util.Lookup;

/**
 *
 * @author djabry
 */
public class ExplorerHolder extends javax.swing.JPanel implements Lookup.Provider,ExplorerManager.Provider{

    /**
     * Creates new form ExplorerHolder
     */
    public ExplorerHolder() {
        initComponents();
    }
    
    private DJNodeObject obj;
    
    public DJNodeObject getRoot(){
        
        return obj;
    }
    
    private ExplorerManager eM;
    private Lookup lookup;
    private JComponent exComp;
    
    public void initExplorer(DJNodeObject obj){
        this.obj=obj;
        this.eM=new ExplorerManager();
        this.eM.setRootContext(new DJNode(obj));
        this.lookup=ExplorerUtils.createLookup(this.eM, getActionMap());
        
        
        
    }
    
    public JComponent getExplorerComponent(){
        
        return this.exComp;
    }
    
    public void setExplorerComponent(JComponent c){
        if(exComp!=null){
            this.remove(exComp);
        }
        setSize(new java.awt.Dimension(100, 100));
        setLayout(new java.awt.GridLayout(1, 1,5,5));
        
        this.add(c);
        
        exComp=c;
        
         if(this.exComp instanceof TreeView){
            
            //((TreeView)this.exComp).setRootVisible(false);
            ((TreeView)this.exComp).setDragSource(true);
        }
        
        
        if(this.exComp instanceof ListView){
            
            ((ListView)this.exComp).setDragSource(true);
            
            
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setSize(new java.awt.Dimension(100, 100));
        setLayout(new java.awt.GridLayout(1, 0, 5, 5));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public Lookup getLookup() {
        return this.lookup;
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return this.eM;
        
    }
}
