/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.dj.worldwindmodel.globeviewer.editor;

import gov.nasa.worldwind.WorldWindow;
import gov.nasa.worldwind.util.StatusBar;
import gov.nasa.worldwindx.examples.FlatWorldPanel;
import java.awt.Component;
import java.awt.EventQueue;
import org.dj.worldwindmodel.globe.api.GlobeManager;
import org.dj.worldwindmodel.globeviewer.api.GlobeService;
import org.dj.worldwindmodel.globeviewer.api.Projection;
import org.dj.worldwindmodel.worldwindow.api.WorldWindowService;
import org.openide.util.Lookup;

/**
 *
 * @author djabry
 */
public class GlobePanel extends javax.swing.JPanel {
    
    private GlobeManager manager;
    private static final WorldWindowService wS = Lookup.getDefault().lookup(WorldWindowService.class);
    private static final GlobeService gS = Lookup.getDefault().lookup(GlobeService.class);
    
    /**
     * Creates new form GlobePanel
     */
    public GlobePanel() {
        initComponents();
    }

    
    public GlobePanel(GlobeManager mgr){
        
        this();
        this.manager=mgr;
        
        //This makes loading slightly smoother
        Runnable r= new Runnable() {

            @Override
            public void run() {
                WorldWindow wW = wS.createObject(manager);
                StatusBar sB = new StatusBar();
                sB.setEventSource(wW);
                statusBarHolder.add(sB);
                worldWindowHolder.add((Component)wW);

            }
        };
        
        EventQueue.invokeLater(r);

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        projectionCombo = new javax.swing.JComboBox();
        worldWindowHolder = new javax.swing.JPanel();
        statusBarHolder = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jToolBar1.setRollover(true);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(GlobePanel.class, "GlobePanel.jLabel1.text")); // NOI18N
        jToolBar1.add(jLabel1);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(GlobePanel.class, "GlobePanel.jLabel2.text")); // NOI18N
        jToolBar1.add(jLabel2);

        projectionCombo.setModel(new javax.swing.DefaultComboBoxModel(Projection.values()));
        projectionCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectionComboActionPerformed(evt);
            }
        });
        jToolBar1.add(projectionCombo);

        worldWindowHolder.setLayout(new java.awt.GridLayout(1, 0));

        statusBarHolder.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                    .addComponent(statusBarHolder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(worldWindowHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(worldWindowHolder, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusBarHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void projectionComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectionComboActionPerformed
        // TODO add your handling code here:
        gS.createObject(manager).setProjection((Projection)this.projectionCombo.getSelectedItem());
        
    }//GEN-LAST:event_projectionComboActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JComboBox projectionCombo;
    private javax.swing.JPanel statusBarHolder;
    private javax.swing.JPanel worldWindowHolder;
    // End of variables declaration//GEN-END:variables
}
