/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.dj.defaulteditor;
import org.dj.node.api.DJNode;
import org.dj.domainmodel.api.DJNodeObject;
import org.openide.nodes.Node;

/**
 *
 * @author djabry
 */
public class DefaultEditorPanel extends javax.swing.JPanel {
    
    private final DJNodeObject obj;
    private final DJNode n;

    /**
     * Creates new form DefaultEditor
     */
    public DefaultEditorPanel(DJNodeObject obj) {
        initComponents();
        this.obj=  obj;
        this.n=new DJNode(obj);
        this.propertySheet1.setNodes(new Node[]{n});
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        propertySheet1 = new org.openide.explorer.propertysheet.PropertySheet();

        setLayout(new java.awt.GridLayout(1, 0));
        add(propertySheet1);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openide.explorer.propertysheet.PropertySheet propertySheet1;
    // End of variables declaration//GEN-END:variables
}
