/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.lblrtm.task.editor;

import org.lblrtm.task.api.LBLRTMParallelTask;
import org.netbeans.api.options.OptionsDisplayer;

/**
 *
 * @author djabry
 */
public class HostSelector extends javax.swing.JPanel {

    private final LBLRTMParallelTask tsk;
    /**
     * Creates new form HostSelector
     */
    public HostSelector(LBLRTMParallelTask tsk) {
        this.tsk=tsk;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hostSelector = new HostSelectorCombo(tsk);
        configure = new javax.swing.JButton();

        hostSelector.setModel(hostSelector.getModel());
        hostSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostSelectorActionPerformed(evt);
            }
        });

        configure.setText(org.openide.util.NbBundle.getMessage(HostSelector.class, "HostSelector.configure.text")); // NOI18N
        configure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(hostSelector, 0, 202, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(configure, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(hostSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(configure, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void configureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configureActionPerformed
        // TODO add your handling code here:
        OptionsDisplayer.getDefault().open("LBLRTM/Hosts");
    }//GEN-LAST:event_configureActionPerformed

    private void hostSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hostSelectorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton configure;
    private javax.swing.JComboBox hostSelector;
    // End of variables declaration//GEN-END:variables
}
