/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.lblrtm.task.editor;

import org.lblrtm.task.api.DoubleEditorField;
import javax.swing.JTextField;
import org.dj.property.api.DJProperty;
import org.lblrtm.lblrtmdata.api.Surface;
import org.lblrtm.lblrtmdata.api.SurfaceAbstr;

/**
 *
 * @author djabry
 */
public class SurfaceEditorPanel extends javax.swing.JPanel {

    /**
     * Creates new form SurfaceEditorPanel
     */
    
    private final Surface surf;
    
    public SurfaceEditorPanel(Surface s) {
         this.surf=s;
        initComponents();
       
        this.addEditorComponents();
        
    }
    
    private void addEditorComponents(){

        for(int i = 0;i<3;i++){
            DJProperty p = surf.getProperty(SurfaceAbstr.generateEmissionCoeffName(i));
            JTextField f  =new DoubleEditorField(p);
            f.setText(p.getValue().toString());
            this.valuePanel.add(f);
        }
        
        for(int i = 0;i<3;i++){
            DJProperty p = surf.getProperty(SurfaceAbstr.generateReflectionCoeffName(i));
            JTextField f  =new DoubleEditorField(p);
            f.setText(p.getValue().toString());
            this.valuePanel.add(f);
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        valuePanel = new javax.swing.JPanel();
        surfaceTypeCombo = new SurfaceTypeCombo(this.surf);
        surfaceTemp = new DoubleEditorField(this.surf.getProperty(Surface.PROP_SURFACE_TEMP));

        labelPanel.setLayout(new java.awt.GridLayout(0, 1));

        jLabel4.setText(org.openide.util.NbBundle.getMessage(SurfaceEditorPanel.class, "SurfaceEditorPanel.jLabel4.text")); // NOI18N
        labelPanel.add(jLabel4);

        jLabel5.setText(org.openide.util.NbBundle.getMessage(SurfaceEditorPanel.class, "SurfaceEditorPanel.jLabel5.text")); // NOI18N
        labelPanel.add(jLabel5);

        jLabel11.setText(org.openide.util.NbBundle.getMessage(SurfaceEditorPanel.class, "SurfaceEditorPanel.jLabel11.text")); // NOI18N
        labelPanel.add(jLabel11);

        jLabel13.setText(org.openide.util.NbBundle.getMessage(SurfaceEditorPanel.class, "SurfaceEditorPanel.jLabel13.text")); // NOI18N
        labelPanel.add(jLabel13);

        jLabel14.setText(org.openide.util.NbBundle.getMessage(SurfaceEditorPanel.class, "SurfaceEditorPanel.jLabel14.text")); // NOI18N
        labelPanel.add(jLabel14);

        jLabel10.setText(org.openide.util.NbBundle.getMessage(SurfaceEditorPanel.class, "SurfaceEditorPanel.jLabel10.text")); // NOI18N
        labelPanel.add(jLabel10);

        jLabel12.setText(org.openide.util.NbBundle.getMessage(SurfaceEditorPanel.class, "SurfaceEditorPanel.jLabel12.text")); // NOI18N
        labelPanel.add(jLabel12);

        jLabel9.setText(org.openide.util.NbBundle.getMessage(SurfaceEditorPanel.class, "SurfaceEditorPanel.jLabel9.text")); // NOI18N
        labelPanel.add(jLabel9);

        valuePanel.setLayout(new java.awt.GridLayout(0, 1, 0, 6));

        surfaceTypeCombo.setModel(surfaceTypeCombo.getModel());
        valuePanel.add(surfaceTypeCombo);

        surfaceTemp.setText(this.surf.getProperty(Surface.PROP_SURFACE_TEMP).getValue().toString());
        surfaceTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surfaceTempActionPerformed(evt);
            }
        });
        valuePanel.add(surfaceTemp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(valuePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(valuePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void surfaceTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surfaceTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surfaceTempActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel labelPanel;
    private javax.swing.JTextField surfaceTemp;
    private javax.swing.JComboBox surfaceTypeCombo;
    private javax.swing.JPanel valuePanel;
    // End of variables declaration//GEN-END:variables
}
