/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.dj.plot;

import java.io.IOException;
import org.dj.plot.api.Plottable;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.openide.util.Exceptions;

/**
 *
 * @author djabry
 */
public class DJChartPanel extends javax.swing.JPanel {

    /**
     * Creates new form DJChartPanel
     */
    public DJChartPanel(JFreeChart c,Plottable p) {
        initComponents();
        this.c=c;
        this.cP=new ChartPanel(c);
        this.cPanel.add(this.cP);
        this.p=p;
        
        
    }
    
    private final JFreeChart c;
    private final ChartPanel cP;
    private final Plottable p;
    
    
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cPanel = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        exportData = new javax.swing.JButton();

        cPanel.setLayout(new java.awt.GridLayout(1, 1));

        jToolBar1.setRollover(true);

        exportData.setText(org.openide.util.NbBundle.getMessage(DJChartPanel.class, "DJChartPanel.exportData.text")); // NOI18N
        exportData.setFocusable(false);
        exportData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exportData.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        exportData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportDataActionPerformed(evt);
            }
        });
        jToolBar1.add(exportData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void exportDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportDataActionPerformed
        try {
            // TODO add your handling code here:
            this.p.exportData();
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_exportDataActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cPanel;
    private javax.swing.JButton exportData;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
